### PR TITLE
Improve the description

### PR DESCRIPTION
**Pull request by Amanej**

### CODE REVIEW

**Comment by scanf** [comment]
I see different commit authors. @Amanej Is this ready to be merged or do you want todo something first?

**Comment by Amanej** [comment]
I was just using my old github account.

tor. 31. okt. 2019 kl. 06:04 skrev Alexander Alemayhu <
notifications@github.com>:

**Comment by scanf** [comment]
Can you squash? Then it should be good to merge.

**Comment by scanf** [comment]
Thanks for following up in https://github.com/JAMstack-Oslo/org-website/pull/8

**Pull request closed without merging**
